version: '3'

services:
  app:
    container_name: http_service_topcoin
    build:
      context: ./../
      dockerfile: ./build/dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./../:/usr/src/app
    depends_on:
      - db
    links:
      - db
  grpcapp:
    container_name: grpc_service_topcoin
    build:
      context: ./../
      dockerfile: ./build/grpc/dockerfile
    ports:
      - 8090:8090
    volumes:
      - ./../:/usr/src/app
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8096:80
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: coins
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - /home/pwasi/Desktop/golang/topcoin/deployments/db/:/docker-entrypoint-initdb.d
  topcollector:
    container_name: topcollector
    build:
      context: ./../services/topcollector
      dockerfile: ./build/dockerfile
    ports:
      - 8070:8070
    volumes:
      - ./../:/usr/src/app
  cron:
    container_name: cron
    build:
      context: ./../services/cron
      dockerfile: ./build/dockerfile
    ports:
      - 8075:8075
    volumes:
      - ./../:/usr/src/app
  coinmarket:
    container_name: coinmarket
    build:
      context: ./../services/coinmarket
      dockerfile: ./build/dockerfile
    ports:
      - 8060:8060
    volumes:
      - ./../:/usr/src/app
  grpccoinmarket:
    container_name: grpc_coinmarket
    build:
      context: ./../services/coinmarket
      dockerfile: ./build/grpc/dockerfile
    ports:
      - 8061:8061
    volumes:
      - ./../:/usr/src/app
  cryptocompare:
    container_name: cryptocompare
    build:
      context: ./../services/cryptocompare
      dockerfile: ./build/dockerfile
    ports:
      - 8050:8050
    volumes:
      - ./../:/usr/src/app
  grpccryptocompare:
    container_name: grpc_cryptocompare
    build:
      context: ./../services/cryptocompare
      dockerfile: ./build/grpc/dockerfile
    ports:
      - 8051:8051
    volumes:
      - ./../:/usr/src/app
volumes:
  db: { }
