version: '3'

services:
  app:
    container_name: http_service_topcoin
    build:
      context: ./../
      dockerfile: ./build/dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./../:/usr/src/app
  topcollector:
    container_name: topcollector
    build:
      context: ./../services/topcollector
      dockerfile: ./build/dockerfile
    ports:
      - 8070:8070
    volumes:
      - ./../:/usr/src/app
  coinmarket:
    container_name: coinmarket
    build:
      context: ./../services/coinmarket
      dockerfile: ./build/dockerfile
    ports:
      - 8060:8060
    volumes:
      - ./../:/usr/src/app
  cryptocompare:
    container_name: cryptocompare
    build:
      context: ./../services/cryptocompare
      dockerfile: ./build/dockerfile
    ports:
      - 8050:8050
    volumes:
      - ./../:/usr/src/app
