version: '3'

services:
  app:
    container_name: topcoin
    build:
      context: ./../
      dockerfile: ./build/package/dockerfile
    ports:
      - 8080:8080
    restart: on-failure:10
    volumes:
      - ./../:/usr/src/app
volumes:
  database: { }
  cache:
