// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topcollector.proto

package topcollector

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopData struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=Rank,proto3" json:"Rank,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=Score,proto3" json:"Score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopData) Reset()         { *m = TopData{} }
func (m *TopData) String() string { return proto.CompactTextString(m) }
func (*TopData) ProtoMessage()    {}
func (*TopData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd4775f75c8f415, []int{0}
}

func (m *TopData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopData.Unmarshal(m, b)
}
func (m *TopData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopData.Marshal(b, m, deterministic)
}
func (m *TopData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopData.Merge(m, src)
}
func (m *TopData) XXX_Size() int {
	return xxx_messageInfo_TopData.Size(m)
}
func (m *TopData) XXX_DiscardUnknown() {
	xxx_messageInfo_TopData.DiscardUnknown(m)
}

var xxx_messageInfo_TopData proto.InternalMessageInfo

func (m *TopData) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TopData) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *TopData) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type TopResponse struct {
	Coin                 []*TopData `protobuf:"bytes,1,rep,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TopResponse) Reset()         { *m = TopResponse{} }
func (m *TopResponse) String() string { return proto.CompactTextString(m) }
func (*TopResponse) ProtoMessage()    {}
func (*TopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd4775f75c8f415, []int{1}
}

func (m *TopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopResponse.Unmarshal(m, b)
}
func (m *TopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopResponse.Marshal(b, m, deterministic)
}
func (m *TopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopResponse.Merge(m, src)
}
func (m *TopResponse) XXX_Size() int {
	return xxx_messageInfo_TopResponse.Size(m)
}
func (m *TopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopResponse proto.InternalMessageInfo

func (m *TopResponse) GetCoin() []*TopData {
	if m != nil {
		return m.Coin
	}
	return nil
}

type TopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopRequest) Reset()         { *m = TopRequest{} }
func (m *TopRequest) String() string { return proto.CompactTextString(m) }
func (*TopRequest) ProtoMessage()    {}
func (*TopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd4775f75c8f415, []int{2}
}

func (m *TopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopRequest.Unmarshal(m, b)
}
func (m *TopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopRequest.Marshal(b, m, deterministic)
}
func (m *TopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopRequest.Merge(m, src)
}
func (m *TopRequest) XXX_Size() int {
	return xxx_messageInfo_TopRequest.Size(m)
}
func (m *TopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TopData)(nil), "TopData")
	proto.RegisterType((*TopResponse)(nil), "TopResponse")
	proto.RegisterType((*TopRequest)(nil), "TopRequest")
}

func init() { proto.RegisterFile("topcollector.proto", fileDescriptor_fdd4775f75c8f415) }

var fileDescriptor_fdd4775f75c8f415 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xc9, 0x2f, 0x48,
	0xce, 0xcf, 0xc9, 0x49, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2,
	0xe6, 0x62, 0x0f, 0xc9, 0x2f, 0x70, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe3, 0x62, 0x0b, 0xae, 0xcc,
	0x4d, 0xca, 0xcf, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x84, 0xb8, 0x58,
	0x82, 0x12, 0xf3, 0xb2, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e,
	0xd6, 0xe0, 0xe4, 0xfc, 0xa2, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0x08, 0x47, 0x49,
	0x9b, 0x8b, 0x3b, 0x24, 0xbf, 0x20, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x86,
	0x8b, 0x25, 0x39, 0x3f, 0x33, 0x4f, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x43, 0x0f, 0x6a,
	0x51, 0x10, 0x58, 0x54, 0x89, 0x87, 0x8b, 0x0b, 0xac, 0xb8, 0xb0, 0x34, 0xb5, 0xb8, 0xc4, 0xc8,
	0x8a, 0x8b, 0x27, 0x24, 0xbf, 0xc0, 0x19, 0xe6, 0x3a, 0x21, 0x2d, 0x2e, 0x5e, 0xf7, 0xd4, 0x12,
	0xdf, 0xd4, 0xa2, 0xf4, 0xd4, 0x14, 0xb0, 0xeb, 0xb8, 0xf5, 0x10, 0xaa, 0xa5, 0x78, 0xf4, 0x90,
	0xec, 0x49, 0x62, 0x03, 0x7b, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x10, 0x9c, 0x82,
	0xe0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopCollectorClient is the client API for TopCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopCollectorClient interface {
	GetMergedData(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopResponse, error)
}

type topCollectorClient struct {
	cc *grpc.ClientConn
}

func NewTopCollectorClient(cc *grpc.ClientConn) TopCollectorClient {
	return &topCollectorClient{cc}
}

func (c *topCollectorClient) GetMergedData(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopResponse, error) {
	out := new(TopResponse)
	err := c.cc.Invoke(ctx, "/TopCollector/GetMergedData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopCollectorServer is the server API for TopCollector service.
type TopCollectorServer interface {
	GetMergedData(context.Context, *TopRequest) (*TopResponse, error)
}

// UnimplementedTopCollectorServer can be embedded to have forward compatible implementations.
type UnimplementedTopCollectorServer struct {
}

func (*UnimplementedTopCollectorServer) GetMergedData(ctx context.Context, req *TopRequest) (*TopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMergedData not implemented")
}

func RegisterTopCollectorServer(s *grpc.Server, srv TopCollectorServer) {
	s.RegisterService(&_TopCollector_serviceDesc, srv)
}

func _TopCollector_GetMergedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopCollectorServer).GetMergedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TopCollector/GetMergedData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopCollectorServer).GetMergedData(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopCollector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TopCollector",
	HandlerType: (*TopCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMergedData",
			Handler:    _TopCollector_GetMergedData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topcollector.proto",
}
